name: /kyukon/data/gent/vo/000/gvo00082/research/ICT/VAL/Revio_PureTarget/conda
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bcftools=1.22=h3a4d415_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - gsl=2.7=he838d99_0
  - htslib=1.22.1=h566b1c6_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libblas=3.9.0=34_h59b9bed_openblas
  - libcblas=3.9.0=34_he106b2a_openblas
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgfortran=15.1.0=h69a702a_4
  - libgfortran5=15.1.0=hcea5267_4
  - libgomp=15.1.0=h767d61c_4
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libopenblas=0.3.30=pthreads_h94d23a6_1
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - mosdepth=0.3.11=h0ec343a_1
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.2=h26f9b46_0
  - pbmm2=1.17.0=h9ee0642_0
  - pbtk=3.5.0=h9ee0642_0
  - perl=5.32.1=7_hd590300_perl5
  - pip=25.2=pyh145f28c_0
  - python=3.13.5=hec9711d_102_cp313
  - python_abi=3.13=8_cp313
  - readline=8.2=h8c095d6_2
  - samtools=1.22.1=h96c455f_0
  - tabulate=0.9.0=py313h06a4308_0
  - tk=8.6.13=noxft_hd72426e_102
  - trgt=4.0.0=h9ee0642_0
  - tzdata=2025b=h78e105d_0
  - zstd=1.5.7=hb8e6e7a_2
prefix: /kyukon/data/gent/vo/000/gvo00082/research/ICT/VAL/Revio_PureTarget/conda
